config/routes.rb
Achatesadvisorsfinal::Application.routes.draw do

  get "about/index"

  devise_for :admins

  root :to => 'pages#show', id: '1'

  resources :pages, only: [ :index, :show ]

  get 'contactus' => 'pages#show', id: '2', as: 'contact'
  get 'aboutus' => 'about#index', as: 'about'

  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    resources :pages
    resources :admins
    resources :dynamic_contents
    resources :employees
  end

end

app/views/admin/pages/_form.html.erb
<%= form_for([:admin, @page]) do |f| %>
    <table class="table">
      <tr>
        <td colspan="2">
          <% if @page.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

                <ul>
                  <% @page.errors.full_messages.each do |msg| %>
                      <li><%= msg %></li>
                  <% end %>
                </ul>
              </div>
          <% end %>
        </td>
      </tr>
      <tr>
        <td valign="top">Page Title:</td>
        <td valign="top"><%= f.text_field :title, class: 'form-control' %></td>
      </tr>
      <tr>
        <td valign="top">Permalink:</td>
        <td valign="top"><%= f.text_field :slug, class: 'form-control' %></td>
      </tr>
      <tr>
        <td valign="top">Content:</td>
        <td valign="top"><%= f.text_area :content %></td>
      </tr>
      <tr>
        <td colspan="2" valign="top"><%= f.submit 'Save', class: 'btn btn-success btn-sm' %></td>
      </tr>
    </table>
<% end %>

app/views/admin/pages/edit.html.erb
<h4>Edit page</h4>
<%= render 'form' %>

app/views/admin/pages/index.html.erb
<table width="100%" border="0">
  <tr>
    <td align="right"><%= link_to 'New Page', new_admin_page_path, class: 'btn btn-success btn-sm' %></td>
  </tr>
</table>
<hr>
<h4>Manage Pages</h4>

<table class="table">
  <tr>
    <th>Title</th>
    <th>Permalink</th>
    <th></th>
  </tr>

<% @pages.each do |page| %>
  <tr>
    <td><%= link_to page.title, admin_page_path(page) %></td>
    <td><%= page.slug %></td>
    <td align="right"><%= link_to 'Edit', edit_admin_page_path(page), class: 'btn btn-warning btn-sm' %> <%= link_to 'Delete', admin_page_path(page), :method => :delete, data: { confirm: 'Are you sure you want to delete this page?' }, class: 'btn btn-danger btn-sm' %></td>
  </tr>
<% end %>
</table>

app/views/admin/pages/new.html.erb
<h4>New page</h4>

<%= render 'form' %>

app/views/admin/pages/show.html.erb
<table width="100%" border="0">
  <tr>
    <td align="right"><%= link_to 'Edit', edit_admin_page_path(@page), class: 'btn btn-warning btn-sm' %>
      <%= link_to 'Back to all pages', admin_pages_path, class: 'btn btn-default btn-sm' %></td>
  </tr>
</table>
<hr>
<p><%= raw(@page.content) %></p>