config/routes.rb
Achatesadvisorsfinal::Application.routes.draw do

  get "about/index"

  devise_for :admins

  root :to => 'pages#show', id: '1'

  resources :pages, only: [ :index, :show ]

  get 'contactus' => 'pages#show', id: '2', as: 'contact'
  get 'aboutus' => 'about#index', as: 'about'

  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    resources :pages
    resources :admins
    resources :dynamic_contents
    resources :employees
  end

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  attr_accessible :details, :employee_image, :name, :resume, :remove_employee_image, :remove_resume
  mount_uploader :employee_image, EmployeeImageUploader
  mount_uploader :resume, ResumeUploader
end

app/controllers/admin/employees_controller.rb
class Admin::EmployeesController < ApplicationController
  before_filter :authenticate_admin!

  layout 'admin'

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @employees }
    end
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    @employee = Employee.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/new
  # GET /employees/new.json
  def new
    @employee = Employee.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/1/edit
  def edit
    @employee = Employee.find(params[:id])
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(params[:employee])

    respond_to do |format|
      if @employee.save
        format.html { redirect_to admin_employee_path(@employee), notice: 'Employee was successfully created.' }
        format.json { render json: @employee, status: :created, location: @employee }
      else
        format.html { render action: "new" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /employees/1
  # PUT /employees/1.json
  def update
    @employee = Employee.find(params[:id])

    respond_to do |format|
      if @employee.update_attributes(params[:employee])
        format.html { redirect_to admin_employee_path(@employee), notice: 'Employee was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to admin_employees_path }
      format.json { head :no_content }
    end
  end


  def remove_employee_image
    employee_image = Employee.find_by_id(params[:employee_image])
    employee_image.remove_employee_image! if employee_image
    redirect_to admin_employees_path
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/admin/employees/_form.html.erb
<%= form_for([:admin, @employee]) do |f| %>
    <table width="100%" border="0" class="table">
      <tr>
        <td colspan="2">
          <% if @employee.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

                <ul>
                  <% @employee.errors.full_messages.each do |msg| %>
                      <li><%= msg %></li>
                  <% end %>
                </ul>
              </div>
          <% end %>
        </td>
      </tr>
      <tr>
        <td width="7%">Name:</td>
        <td width="93%"><%= f.text_field :name, class: 'form-control' %></td>
      </tr>
      <tr>
        <td>Details:</td>
        <td><%= f.text_area :details %></td>
      </tr>
      <tr>
        <td>Image:</td>
        <td><%= f.file_field :employee_image %> <%= f.check_box :remove_employee_image %>  Check here to remove existing image.</td>
      </tr>
      <tr>
        <td>Resume:</td>
        <td><%= f.file_field :resume %> <%= f.check_box :remove_resume %> Check here to remove existing resume.</td>
      </tr>
      <tr>
        <td><%= f.submit 'Save', class: 'btn btn-success btn-sm' %></td>
      </tr>
    </table>


<% end %>

app/views/admin/employees/edit.html.erb
<h4>Edit</h4>

<%= render 'form' %>

app/views/admin/employees/index.html.erb
<table width="100%" border="0">
  <tr>
    <td align="right"><%= link_to 'New Employee', new_admin_employee_path, class: 'btn btn-success btn-sm' %></td>
  </tr>
</table>
<hr>
<h4>Employees</h4>

<table width="100%" class="table">
  <tr>
    <th width="7%"></th>
    <th width="38%">Name</th>
    <th width="34%">Resume</th>
    <th width="21%"></th>
  </tr>

  <% @employees.each do |employee| %>
      <tr>
        <td><% if !employee.employee_image.to_s.empty? %><%= image_tag employee.employee_image.url(:thumb).to_s %><% end %></td>
        <td><%= link_to employee.name, admin_employee_path(employee) %></td>
        <td><% if !employee.resume.to_s.empty? %><%= link_to 'Download', employee.resume.to_s %><% end %></td>
        <td align="right"><%= link_to 'Edit', edit_admin_employee_path(employee), class: 'btn btn-warning btn-sm' %> <%= link_to 'Delete', admin_employee_path(employee), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %></td>
      </tr>
  <% end %>
</table>

app/views/admin/employees/new.html.erb
<h4>New Employee</h4>

<%= render 'form' %>

app/views/admin/employees/show.html.erb
<h4><%= @employee.name %></h4>
<p><% if !@employee.employee_image.to_s.empty? %><%= image_tag @employee.employee_image.to_s, class:'img-float-right' %><% end %> <%= raw @employee.details %></p>
<% if !@employee.resume.to_s.empty? %>
<p><i class="fa fa-download"></i> <%= link_to 'Download My Resume', @employee.resume.to_s %></p>
<% end %>