config/routes.rb
Achatesadvisorsfinal::Application.routes.draw do

  get "about/index"

  devise_for :admins

  root :to => 'pages#show', id: '1'

  resources :pages, only: [ :index, :show ]

  get 'contactus' => 'pages#show', id: '2', as: 'contact'
  get 'aboutus' => 'about#index', as: 'about'

  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    resources :pages
    resources :admins
    resources :dynamic_contents
    resources :employees
  end

end

app/views/admin/admins/_form.html.erb
<%= form_for([:admin, @admin]) do |f| %>
    <table class="table">
      <tr>
        <td colspan="2">
          <% if @admin.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@admin.errors.count, "error") %> prohibited this page from being saved:</h2>

                <ul>
                  <% @admin.errors.full_messages.each do |msg| %>
                      <li><%= msg %></li>
                  <% end %>
                </ul>
              </div>
          <% end %>
        </td>
      </tr>
      <tr>
        <td valign="top">Email:</td>
        <td valign="top"><%= f.text_field :email, class: 'form-control' %></td>
      </tr>
      <tr>
        <td valign="top">Password:</td>
        <td valign="top"><%= f.text_field :password, class: 'form-control' %></td>
      </tr>
      <tr>
        <td valign="top">Password Confirmation:</td>
        <td valign="top"><%= f.text_field :password_confirmation, class: 'form-control' %></td>
      </tr>
      <tr>
        <td colspan="2" valign="top"><%= f.submit 'Save', class: 'btn btn-success btn-sm' %></td>
      </tr>
    </table>
<% end %>

app/views/admin/admins/edit.html.erb
<h4>Edit Administrator</h4>
<%= render 'form' %>

app/views/admin/admins/index.html.erb
<table width="100%" border="0">
  <tr>
    <td align="right"><%= link_to 'New administrator', new_admin_admin_path, class: 'btn btn-success btn-sm' %></td>
  </tr>
</table>
<hr>
<h4>Administrators</h4>

<table class="table table-hover">
  <tr>
    <th>Email</th>
    <th>Encrypted Password</th>
    <th></th>
  </tr>

  <% @admins.each do |admin| %>
      <tr>
        <td><%= link_to admin.email, admin_admin_path(admin) %></td>
        <td><%= admin.encrypted_password %></td>
        <td><%= link_to 'Edit', edit_admin_admin_path(admin), class: 'btn btn-warning btn-sm' %> <%= link_to 'Delete', admin_admin_path(admin), :method => :delete, data: { confirm: 'Are you sure you want to delete this administrator?' }, class: 'btn btn-danger btn-sm' %></td>
      </tr>
  <% end %>
</table>

app/views/admin/admins/new.html.erb
<h4>New administrator</h4>

<%= render 'form' %>

app/views/admin/admins/show.html.erb
<table width="100%" border="0">
  <tr>
    <td align="right"><%= link_to 'Edit', edit_admin_admin_path(@admin), class: 'btn btn-warning btn-sm' %>
      <%= link_to 'Back to all pages', admin_admins_path, class: 'btn btn-default btn-sm' %></td>
  </tr>
</table>
<hr>
<h4><%= @admin.email %></h4>