config/routes.rb
Achatesadvisorsfinal::Application.routes.draw do

  get "about/index"

  devise_for :admins

  root :to => 'pages#show', id: '1'

  resources :pages, only: [ :index, :show ]

  get 'contactus' => 'pages#show', id: '2', as: 'contact'
  get 'aboutus' => 'about#index', as: 'about'

  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    resources :pages
    resources :admins
    resources :dynamic_contents
    resources :employees
  end

end

app/views/layouts/_employee-loop.html.erb
<% @all_employees.each do |employee| %>
    <h4><%= employee.name %></h4>
    <p><% if !employee.employee_image.to_s.empty? %><%= image_tag employee.employee_image.to_s, class:'img-float-right' %><% end %> <%= raw employee.details %></p>
    <% if !employee.resume.to_s.empty? %>
        <p><i class="fa fa-download"></i> <%= link_to 'Download My Resume', employee.resume.to_s %></p>
    <% end %>
    <hr>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Achates Capital Advisors, LLC</title>
  <link href="http://netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
  <link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet">
  <link href="https://s3.amazonaws.com/achatesadvisors/app/assets/stylesheets/my_styles.css" rel="stylesheet">
  <%= stylesheet_link_tag 'application.css' %>
  <script src="//tinymce.cachefly.net/4.0/tinymce.min.js"></script>
  <%= javascript_include_tag "application" %>
  <script>
      tinymce.init({
          selector:'textarea',
          plugins: [
              "advlist autolink link lists charmap print preview hr anchor pagebreak spellchecker",
              "searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking",
              "save table contextmenu directionality emoticons template paste textcolor"
          ]
      });
  </script>
  <%= csrf_meta_tags %>
</head>
<body>




<div class="container  container-bg-white">
  <div class="row">
    <div class="col-md-4"><%= link_to 'Achates Capital Advisors, LLC', root_path, class: 'navbar-brand' %></div>
    <div class="col-md-8 masthead-address">
      <ul class="list-inline">
        <li><i class="fa fa-home"></i> <%= strip_tags(@contact_address) %></li>
      </ul>
    </div>
  </div>
</div>


<div class="container container-bg-white">
  <!---  BEGIN MAIN CONTENT ROW -->
  <div class="row">
    <div class="col-md-3">
      <ul class="nav nav-pills nav-stacked">
        <li class="<%= 'active' if current_page?admin_path %>"><%= link_to 'Dashboard', admin_path %></li>
        <li class="<%= 'active' if current_page?admin_pages_path %>"><%= link_to 'Manage Pages', admin_pages_path %></li>
        <li class="<%= 'active' if current_page?admin_dynamic_contents_path %>"><%= link_to 'Manage Snippets', admin_dynamic_contents_path %></li>
        <li class="<%= 'active' if current_page?admin_employees_path %>"><%= link_to 'Manage Employees', admin_employees_path %></li>
        <li class="<%= 'active' if current_page?admin_admins_path %>"><%= link_to 'Manage Website Administrators', admin_admins_path %></li>
        <li><%= link_to 'Logout', destroy_admin_session_path(protocol: 'https'), :method => :delete %></li>
      </ul>
    </div>
    <div class="col-md-9">
      <%= yield %>

    </div>
  </div>
  <!---  END MAIN CONTENT ROW -->

</div> <!-- /container -->
<div class="container" id="footer">
  <ul class="list-inline">
    <li><i class="fa fa-home"></i> <%= strip_tags(@contact_address) %></li>
    <li><i class="fa fa-phone"></i> <%= strip_tags(@contact_phone) %></li>
  </ul>
</div>




<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
<script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Achates Capital Advisors, LLC</title>
  <link href="http://netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
  <link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet">
  <%= stylesheet_link_tag 'application.css' %>
  <script src="//tinymce.cachefly.net/4.0/tinymce.min.js"></script>
  <%= javascript_include_tag "application" %>
  <script>
      tinymce.init({
          selector:'textarea',
          plugins: [
              "advlist autolink link lists charmap print preview hr anchor pagebreak spellchecker",
              "searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking",
              "save table contextmenu directionality emoticons template paste textcolor"
          ]
      });
  </script>
  <%= csrf_meta_tags %>
</head>
<body>




<div class="container  container-bg-white border-top">
  <div class="row">
    <div class="col-md-2"><%= image_tag 'https://s3.amazonaws.com/achatesadvisors/app/assets/images/logo.jpg' %></div>
    <div class="col-md-4"><%= link_to 'Achates Capital Advisors, LLC', root_path, class: 'navbar-brand' %></div>
    <div class="col-md-6 masthead-address">
      <ul class="list-inline">
        <li><i class="fa fa-home"></i> <%= strip_tags(@contact_address) %></li>
      </ul>
    </div>
  </div>
</div>


<div class="container container-bg-white">
  <!---  BEGIN MAIN CONTENT ROW -->
  <div class="row">
    <div class="col-md-3">
      <ul class="nav nav-pills nav-stacked">
        <li class="<%= 'active' if current_page?root_path %>"><%= link_to 'Home', root_path %></li>
        <li class="<%= 'active' if current_page?about_path %>"><%= link_to 'About Us', about_path %></li>
        <li class="<%= 'active' if current_page?contact_path %>"><%= link_to 'Contact Us', contact_path %></li>
      </ul>
    </div>
    <div class="col-md-9">
      <%= yield %>


    </div>
  </div>
  <!---  END MAIN CONTENT ROW -->

</div> <!-- /container -->
<div class="container" id="footer">
  <ul class="list-inline">
    <li><i class="fa fa-home"></i> <%= strip_tags(@contact_address) %></li>
    <li><i class="fa fa-phone"></i> <%= strip_tags(@contact_phone) %></li>
  </ul>
</div>




<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
<script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
</body>
</html>